# \u6CE8\u610F\u8FD9\u662F\u57FA\u4E8E\u6C99\u7BB1\u73AF\u5883\u6A21\u62DF\u7684\u64CD\u4F5C,\u771F\u5B9E\u64CD\u4F5C\u8BF7\u4E0D\u8981\u66B4\u9732\u4F60\u7684\u4FE1\u606F
alipay:
  #  \u5E94\u7528ID,\u60A8\u7684APPID\uFF0C\u6536\u6B3E\u8D26\u53F7\u65E2\u662F\u60A8\u7684APPID\u5BF9\u5E94\u652F\u4ED8\u5B9D\u8D26\u53F7
  appId: 2016110100783730
  #  \u5546\u6237\u79C1\u94A5\uFF0C\u60A8\u7684PKCS8\u683C\u5F0FRSA2\u79C1\u94A5
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDbMbGN2ZwDMMvc
    5MH7bCvBDfgdoW7eZctMooARV/JRkpFPUiVdc84fFa2QtZm7CoZUGpV8sHnc3SSd
    BM6FkV1IAv+ZtUXp4EatltKyFZiTwrGVfJgkGJE0tCX8vmGWz+JJjShok/pPvTtP
    N7tYJSA3rtbciNggK9fK1I7P4e+LGongPa+cUhnsgMIu8uDJEzzEpssuW61jPsjw
    TtgwDnU+z6o8/QxjeSnjdKGhKgpRv8dOUXxfdruTj60QrlCwp9kMcsl/DyGL9Q0B
    SSlOY3AXXSrUvlZ1IExfw5GvvoutzUxyOgFYz6Fr6X3LtsAyEST76yy3TW7EqAMk
    oaX/HlkVAgMBAAECggEAJ1UTd1DFHg1zh3/FD0ip0UqgazC8pEu/31CJipMteFXE
    nWcwLUTKh+lr67uqilWpJQ5gJK/GLkvAdiyWooEjK/jdxMcydHU6OYwG4s3dQyZ8
    l0Z0RoXiCIMLDf9bo6RKBsi9p4ZmNEjQi7aEd5yx20wUYh5sKdm0L0FVHxh704nq
    XvtDSHMFg0Rz5nY5mE/BF7YZndXGTNUsash326YMWfUQq/TLugLM0c1yL8x8rj8I
    x75OFd6hkSe/Shy2ugPYxCJXFPSGafvHUXJgiC7HiTgqsM2mYPe88hjg9OGVfuUB
    NO6Q/KtNj02/ne8p87Jj+uSnSDqMhbvt9zYMxQ/WAQKBgQDdfiLW8tm3PcJhn/Ji
    NEn0/SFnelcA6iibXjL4hjhQkwJBGTWm3PXWumYpWOpNZN8VwOcQHwwwVTj2lDvI
    mUbg4G04xIkFGbMhOm9by6c55DEo+WCUT6Pb/InzAlYCHxwlsMLo8tT7ZzONLzRp
    Mjrx04vKuIaiMu/0gB4t9JWA3QKBgQD9V+GtCzSC8AHKjWNpBLwwR+MNlm0S0PTj
    YkkYWLp0FU5l+5r+zZked4x3pUYVggsIes02hcyaOZuqmnz2WxEl+UbNLINs75j3
    rekVuiE5gj4IoKue/4/9PBa5MmdEPEPIf6Q+0KOzBduUZ/FGkSg7OkvUp1BGHpih
    NVGTUJ3ZmQKBgQDIAviZHFIIS+f1Wod5sPg8GD2LAQoCFHG445apoCLIeAhoGsi9
    Nvl0/3vzyIxEeVuOfFTr1O2f08WNvYxC+E7uERvwUGHfTjbZQbh/r2cCOxM9ifxx
    0X0J0YINBMYAQnGbg4Ru8aHsqGQAEWmFuUtLRxoMZReG7vKK2wrluuEqrQKBgB4j
    93hz7dJqJXxop9wVsSH5W30BWYa0j34B8npQDBbFdidR8NXBtibWyEJvyk/CwfdH
    TOTgtD/g/LEmYhmZKggfiRnd4uDx/HvzF9j65PsHkMPMAb8P3pydKoLsCTcoCFRx
    QyQqBF/HIaGdYCoqGOQ7AkyRf05oU3ZSdpsVK0J5AoGAFEEb+kyoQ5gnUnC67GxD
    +K3t3zOUYBr8Sy3hvhihhpN3RW7ESdV6pi3IDBJ5A8fKsePLrpi0tTnZUlddt3LO
    EsvTOD5S/fwuvAzfCvfv/ohp9OtLciIV/TN2STG1rgxxmSMQ43XfVYQiSn8mArSq
    y7X5PWwDXyFKHdafEeFTUnE=
  #  \u652F\u4ED8\u5B9D\u516C\u94A5,\u67E5\u770B\u5730\u5740\uFF1Ahttps://openhome.alipay.com/platform/keyManage.htm \u5BF9\u5E94APPID\u4E0B\u7684\u652F\u4ED8\u5B9D\u516C\u94A5\u3002
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuXmV2YWVfC+YYnuUjYlyK8iEq+AuVZvNI5QQYjpsKncvrrYR07irgu+HGrt+qLQb+iBALEci3g01t3GDXu4RhVETzOVtszAKeGuzf5N7luOOl5SkyWDtfoqYNWH6PDl3NNnqVP92Tz7lOh46gG1lKsw2a7G0i7Z5Z7d18EasvSH3sh/UCmHjaYr5hgPQkrYGzfHNDGYQXb6kphKmCV8+EwX/R2FG5MSHwyG8SKrMcFXTbodIjBUTUO4PPnlNYiWInYPLINz3HTTzunHkR6SoRWh88IAwYl6Jgp5TbtFuYHIgSmG/+kUkhFT5yZxkvDpDvWH2M9LaoF0EioPFnMQ75wIDAQAB
  #  \u670D\u52A1\u5668\u5F02\u6B65\u901A\u77E5\u9875\u9762\u8DEF\u5F84  \u9700http://\u683C\u5F0F\u7684\u5B8C\u6574\u8DEF\u5F84\uFF0C\u4E0D\u80FD\u52A0?id=123\u8FD9\u7C7B\u81EA\u5B9A\u4E49\u53C2\u6570\uFF0C\u5FC5\u987B\u5916\u7F51\u53EF\u4EE5\u6B63\u5E38\u8BBF\u95EE
  notifyUrl: http://127.0.0.1:8080/alipay/notify_url.jsp
  #  \u9875\u9762\u8DF3\u8F6C\u540C\u6B65\u901A\u77E5\u9875\u9762\u8DEF\u5F84 \u9700http://\u683C\u5F0F\u7684\u5B8C\u6574\u8DEF\u5F84\uFF0C\u4E0D\u80FD\u52A0?id=123\u8FD9\u7C7B\u81EA\u5B9A\u4E49\u53C2\u6570\uFF0C\u5FC5\u987B\u5916\u7F51\u53EF\u4EE5\u6B63\u5E38\u8BBF\u95EE
  returnUrl: http://127.0.0.1:8080/alipay/return_url.jsp
  #  \u7B7E\u540D\u65B9\u5F0F
  signType: RSA2
  #  \u5B57\u7B26\u7F16\u7801\u683C\u5F0F
  charset: utf-8
  #  \u652F\u4ED8\u5B9D\u7F51\u5173
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  #  \u6253\u5370\u65E5\u5FD7
  logPath: F:\\